---
- name: Need Backports repositories for installing Icinga Classic UI?
  apt_repository: repo='deb http://archive.canonical.com/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} partner' state=present
  when: ansible_distribution|lower  == 'ubuntu'

- name: Install Icinga Classic UI on Debian OS family
  apt: pkg={{ item.package }} 
       state=latest
       update_cache=yes
       cache_valid_time=30
  with_items: icinga2_classic_ui_pkg

- name: Configure a password for icingaadmin user
  htpasswd: name=icingaadmin
            state=present
            path={{ htpasswd_deb }}
            create=no
            password={{ icinga2_classic_ui_passwd }}
  notify: 
   - restart apache2

- name: Icinga Classic UI Installation finished (Debian)
  debug: msg="Login at http://IP/icinga2-classicui with user icingaadmin and password {{ icinga2_classic_ui_passwd }}"
